"""
Multi-Agent System - Agentes Especializados que Colaboran

System with multiple agents that have different expertise and collaborate.
"""

from dataclasses import dataclass
from typing import List, Dict
from enum import Enum

class AgentRole(Enum):
    RESEARCHER = "researcher"
    ANALYST = "analyst"
    WRITER = "writer"
    COORDINATOR = "coordinator"

@dataclass
class Message:
    """Message between agents."""
    sender: str
    recipient: str
    content: str
    type: str  # "request", "response", "broadcast"

class Agent:
    """Base agent with communication capabilities."""

    def __init__(self, name: str, role: AgentRole, expertise: str):
        self.name = name
        self.role = role
        self.expertise = expertise
        self.inbox: List[Message] = []
        self.memory: List[Dict] = []

    def receive_message(self, message: Message):
        """Receive message from another agent."""
        self.inbox.append(message)
        print(f"📨 {self.name} received: {message.content[:50]}...")

    def process_task(self, task: str) -> str:
        """Process task according to expertise."""
        raise NotImplementedError

    def send_message(self, recipient: str, content: str, msg_type: str = "response") -> Message:
        """Send message to another agent."""
        message = Message(
            sender=self.name,
            recipient=recipient,
            content=content,
            type=msg_type
        )
        print(f"📤 {self.name} → {recipient}: {content[:50]}...")
        return message

class ResearcherAgent(Agent):
    """Agent specialised in information search."""

    def process_task(self, task: str) -> str:
        print(f"\n🔍 {self.name} researching: {task}")

        # Simulation of research
        research_results = {
            "ai agents": "AI agents are autonomous systems that use LLMs to reason and act. Architecture: perception → reasoning → action. Main frameworks: LangChain, AutoGPT.",
            "multi-agent": "Multi-agent systems coordinate multiple specialised agents. Benefits: specialisation, parallelisation, robustness.",
            "langchain": "LangChain is a framework for building LLM applications. Includes agents, chains, memory, and tools."
        }

        for key, value in research_results.items():
            if key in task.lower():
                self.memory.append({"task": task, "result": value})
                return value

        return f"I researched '{task}' but need more context."

class AnalystAgent(Agent):
    """Agent specialised in data analysis."""

    def process_task(self, task: str) -> str:
        print(f"\n📊 {self.name} analysing: {task}")

        # Simulation of analysis
        if "compare" in task.lower():
            analysis = """
            Comparative analysis:
            - LangChain: Better for rapid prototyping, rich ecosystem
            - AutoGPT: More autonomous, less control
            - Custom: Full control, more initial work

            Recommendation: LangChain for MVPs, custom for production at scale
            """
        elif "pros" in task.lower() or "cons" in task.lower():
            analysis = """
            Advantages: Automation, scalability, specialisation
            Disadvantages: Complexity, cost, potential hallucinations
            """
        else:
            analysis = f"Analysis of '{task}': I need more specific data."

        self.memory.append({"task": task, "result": analysis})
        return analysis

class WriterAgent(Agent):
    """Agent specialised in synthesis and writing."""

    def process_task(self, task: str) -> str:
        print(f"\n✍️  {self.name} synthesising: {task}")

        # Compile information from other agents' memory
        # In a real system, it would access received messages

        report = f"""
# Report on {task}

Based on team research and analysis, here is the synthesis:

{task}

This report was collaboratively generated by the multi-agent system.
"""

        self.memory.append({"task": task, "result": report})
        return report


class CoordinatorAgent(Agent):
    """Coordinator agent that orchestrates team work."""

    def __init__(
            self, name: str, team: Dict[str, Agent]):
        super().__init__(
            name,
            AgentRole.COORDINATOR,
            "coordination and task decomposition"
        )
        self.team = team

    def process_task(self, task: str) -> str:
        print(f"\n🎯 {self.name} coordinating task: {task}\n")

        # Decompose task into subtasks
        print("📋 Decomposing task into subtasks...")
        subtasks = self._decompose_task(task)

        results = {}

        # Assign subtasks to specialised agents
        for subtask, agent_role in subtasks:
            agent = self._get_agent_by_role(agent_role)
            if agent:
                # Enviar tarea
                message = self.send_message(
                    recipient=agent.name,
                    content=subtask,
                    msg_type="request"
                )
                agent.receive_message(message)

                # Procesar y guardar result
                result = agent.process_task(subtask)
                results[subtask] = result

                # Recibir response
                response = agent.send_message(
                    recipient=self.name,
                    content=result[:100] + "...",
                    msg_type="response"
                )
                self.receive_message(response)

        # Compile final report
        print("\n📝 Compiling final report...")
        writer = self._get_agent_by_role(AgentRole.WRITER)
        if writer:
            summary = "\n\n".join([f"**{task}**:\n{result}" for task, result in results.items()])
            final_report = writer.process_task(summary)
            return final_report

        return "Task completed but could not generate report."

    def _decompose_task(self, task: str) -> List[tuple]:
        """Decompose task into subtasks + assigned agent."""
        # Simple decomposition logic
        if "report" in task.lower() or "analyse" in task.lower() or "analyze" in task.lower():
            return [
                ("Research main concepts of " + task, AgentRole.RESEARCHER),
                ("Analyse pros and cons of " + task, AgentRole.ANALYST),
                ("Compare mentioned frameworks", AgentRole.ANALYST),
            ]
        else:
            return [
                ("Research " + task, AgentRole.RESEARCHER),
                ("Analyse " + task, AgentRole.ANALYST),
            ]

    def _get_agent_by_role(self, role: AgentRole) -> Agent:
        """Find agent by role."""
        for agent in self.team.values():
            if agent.role == role:
                return agent
        return None


# Demo: Multi-Agent System in action
if __name__ == "__main__":
    print("=" * 60)
    print("🤖 MULTI-AGENT SYSTEM DEMO")
    print("=" * 60)

    # Crear equipo de agents
    team = {
        "researcher": ResearcherAgent("Alice", AgentRole.RESEARCHER, "information gathering"),
        "analyst": AnalystAgent("Bob", AgentRole.ANALYST, "data analysis"),
        "writer": WriterAgent("Carol", AgentRole.WRITER, "synthesis and writing"),
    }

    # Crear coordinator
    coordinator = CoordinatorAgent("Director", team)

    # Complex task requiring collaboration
    task = "Create report on AI Agents: what they are, available frameworks, and use cases"

    # Execute
    final_report = coordinator.process_task(task)

    print("\n\n" + "=" * 60)
    print("📄 FINAL REPORT")
    print("=" * 60)
    print(final_report)

    # Mostrar memoria de cada agente
    print("\n\n" + "=" * 60)
    print("🧠 AGENT MEMORY")
    print("=" * 60)
    for name, agent in team.items():
        print(f"\n{agent.name} ({agent.role.value}):")
        print(f"  Tasks processed: {len(agent.memory)}")
        print(f"  Messages received: {len(agent.inbox)}")

"""
Expected output:

==============================================================
🤖 MULTI-AGENT SYSTEM DEMO
==============================================================

🎯 Director coordinating task: Create report on AI Agents...

📋 Decomposing task into subtasks...
📤 Director → Alice: Research main concepts...
📨 Alice received: Research main concepts...

🔍 Alice researching: Research main concepts...
📤 Alice → Director: AI agents are autonomous systems...
📨 Director received: AI agents are autonomous systems...

[... more interactions ...]

📝 Compiling final report...

✍️  Carol synthesising: ...

==============================================================
📄 FINAL REPORT
==============================================================
# Report on [task]
...

==============================================================
🧠 AGENT MEMORY
==============================================================
Alice (researcher):
  Tasks processed: 1
  Messages received: 1
...
"""
